<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2YwXvyC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2YwXvyC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2YwXvyC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2YwXvyC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2YwXvyC\appAppKernelProdContainer([
    'container.build_hash' => '2YwXvyC',
    'container.build_id' => '082c51b8',
    'container.build_time' => 1711639114,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2YwXvyC');
