<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKSTGXC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKSTGXC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXKSTGXC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXKSTGXC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXKSTGXC\appAppKernelProdContainer([
    'container.build_hash' => 'XKSTGXC',
    'container.build_id' => 'c7f92059',
    'container.build_time' => 1711462651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKSTGXC');
